routes/web.php
<?php

use App\Reservation;
use App\Room;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  $rooms = Room::orderBy('weight')->get();
  return view('welcome', compact('rooms'));
});

Route::get('/book', function () {
  $rooms = Room::where('published', 1)->orderBy('weight')->get();
  return view('rooms', compact('rooms'));
});

Route::get('/book/{room}', 'BookRoomController@show');

Route::get('/book/{room}/unlock', 'BookRoomController@unlock')->name('unlock');

Route::get('/book/{room}/{reservation}', 'BookRoomController@reservation');

Route::put('/book/{room}/{reservation_id}', 'BookRoomController@reservation_id');

Route::get('/thankyou', function () { return view('thankyou'); });

Route::get('/terms', function () { return view('terms'); });

Route::get('/privacy', function () { return view('privacypolicy'); });

Route::get('/instructions', function () { return view('instructions'); });

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/emails', 'EmailsController@show')->middleware('can:view_emails');

Route::get('/editroom', 'EditRoomController@show')->middleware('can:view_emails');

Route::put('/editroom/save', 'EditRoomController@save')->middleware('can:view_emails');

Route::get('/reservations', 'ReservationsController@show')->middleware('can:view_emails');

Route::put('/reservations/add', 'ReservationsController@add')->middleware('can:view_emails');

Route::put('/reservations/confirm', 'ReservationsController@confirm')->middleware('can:view_emails');

Route::put('/reservations/delete', 'ReservationsController@delete')->middleware('can:view_emails');

Route::get('/notify/{room}', 'EmailsController@notify');

Route::put('/notify/{room}', 'EmailsController@adduser');

Route::post('/checkpromo/{code}', 'PromoController@index');

Auth::routes(['register'=>false]);

app/Reservation.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Reservation extends Model {
  protected $guarded = [];

  public function room() {
    return $this->belongsTo('App\Room');
  }

  public function scopeLocked($query) {
    $query->whereNotNull('reservations.locked_at')->where('locked_at', '<', Carbon::now()->sub('10 minutes'));
  }

  public function scopeReserved($query) {
    $query->whereNotNull('reservations.email');
  }

  public function getReservedAttribute() {
    return isset($this->email);
  }

  public function scopeAvailable($query) {
    $this->addAvailableRestrictionToQuery($query);
  }

  public function isAvailable() {
    return !$this->email
      && $this->time > Carbon::now()->addHours(24)
      && (!$this->locked_at || $this->locked_by == request()->session()->getId());
  }

  public function lock() {
    $this->locked_at = Carbon::now();
    $this->locked_by = request()->session()->getId();
    $this->save();
  }

  public function unlock($save = true) {
    if ($this->locked_by != request()->session()->getId()) {
      abort(403);
    }
    $this->locked_at = null;
    $this->locked_by = null;
    if ($save) {
      $this->save();
    }
    return $this;
  }

  public function getFormatedTimeAttribute() {
  return (new Carbon($this->time))->format('d/m/Y \a\t H:i');
  }

  public static function addAvailableRestrictionToQuery($query) {
    $query
      ->whereNull('reservations.email')
      ->where('reservations.time', '>', Carbon::now()->addHours(24))
      ->whereNull('reservations.locked_at');
  }
}

resources/views/book.blade.php
@extends('layout')
@section('pageTitle', $room->title . ' | Online Escape Room by The Web Bunch')
@section('description', $room->description)
@section('canonical', 'https://escape.web-bunch.com/book/' . $room->slug)
@section('ogimagecontent', url('/' . trim('images/og-' . $room->img, '/\\')))
@section('nobutton', 'nobutton')
@section('content')
@if ($message)
  <div class="message">{{ $message }}</div>
@endif
<div class="container">
  <x-room-full :room="$room" />
</div>
<div class="calendar-container">
  @if ($room->available)
  <x-calendar :reservations="$reservations" />
  @else
  <span class="fully-booked">This room is fully booked right now, please check back soon!</span>
  @endif
</div>
@endsection

resources/views/editroom.blade.php
@extends('layout')

@section('content')
  @foreach($rooms as $room)
    <div class="container">
       <form class="edit-room" action="/editroom/save" method="POST">
          @csrf
          @method('PUT')
          <div>
            <h2>Room: {{$room->id}}</h2>
          </div>
          <input type="hidden" value="{{$room->id}}" name="id">
          <div>
            Title: <input type="text" value="{{ $room->title }}" name="title">
          </div>
          <div>
            Description: <textarea name="description">{{ $room->description }}</textarea>
          </div>
          <div>
            Duration: <input type="number" value="{{$room->duration}}" name="duration"> minutes
          </div>
          <div>
          Difficulty: <input type="number" value="{{$room->difficulty}}" max="5" min="1" pattern = "\d{1,5}" name="difficulty">
          </div>
          <div>
          Prices:
          </div>
          @foreach($room->prices as $key => $price)
            <div class="edit-room-price">
            {{$key}} Persons <input type="number" name="price-{{$key}}" min="0" value="{{$price}}"> €
            </div>
          @endforeach
          <div>
            Slug: <input type="text" value="{{$room->slug}}" name="slug">
          </div>
          <div>
            Weight: <input type="number" value="{{$room->weight}}" name="weight">
          </div>
          <div>
            <label>
              Published:
              <input type="checkbox" name="published" value='1' {{$room->published ? 'checked' : ''}}>
            </label>
          </div>
          <button class="update-room">Update</button>
          <span class="last-update">Last update: {{$room->updated_at}}</span>
        </form>
    </div>
  @endforeach

@endsection

resources/views/emails.blade.php
@extends('layout')

@section('content')
  <div class="container">
    <ul class="notified-users">
      @foreach($notifiedusers as $user)
        <li class="notified-user">
          {{ $rooms->find($user->room_id)->title}}
          {{ $user->email }}

        </li>
      @endforeach
    </ul>
  </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/instructions.blade.php
@extends('layout')
@section('pageTitle', 'Instructions before you book | eSCAPE | Online Escape Rooms - by The Web Bunch')
@section('content')
  <div class="container">
    <h1 class="booking-title">Instructions before you book</h1>
    <div class="terms-container">
      <div class="needs">
        <h2 class="inst-title">What you'll need</h2>
        <ul>
          <li>Each player must be at his own personal computer or laptop.</li>
          <li>Solid internet connection.</li>
          <li>Have first-person gaming experience with mouse and keyboard.</li>
          <li>A communication application installed like Discord or Skype. (Discord is preferred)</li>
        </ul>
      </div>
      <div class="needs">
        <h2 class="inst-title">Requirements</h2>
        <ul>
          <li>Minecraft for PC (Java Edition).</li>
          <li>Java.</li>
        </ul>
      </div>
      <div class="needs">
        <h2 class="inst-title">Minecraft: Minimum Requirements</h2>
        <ul>
          <li>CPU: Intel Core i3 3210 | AMD A8 7600 APU or equivalent </li>
          <li>RAM: 4 GB RAM</li>
          <li>HDD: 180 MB to 1 GB available space</li>
          <li>GPU: Intel HD Graphics 4000 or AMD Radeon R5 series | NVIDIA GeForce 400 Series or AMD Radeon HD 7000 series</li>
          <li>OS: 64-bit Windows 7 or later</li>
          <li>Screen Resolution: 1024 x 768 or better</li>
          <li>Network: Broadband Internet connection</li>
        </ul>
      </div>
    </div>
  </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>

<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="favicon.ico" type="image/x-icon" />

        <meta property="og:title" content="@yield('pageTitle', 'eSCAPE | Online Escape Rooms - by The Web Bunch')">
        <meta property="og:description" content="@yield('description', 'A unique experience. Can you escape from our Online Escape Rooms?')">
        <meta property="og:image" content="@yield('ogimagecontent')">

        <title>@yield('pageTitle', 'eSCAPE | Online Escape Rooms - by The Web Bunch')</title>
        <!-- Meta -->
        <meta name="description" content="@yield('description', 'A unique experience. Can you escape from our Online Escape Rooms?')">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:200,500&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Hind:200,500&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
        <!-- Styles -->
        <link rel="stylesheet" href="{{mix('css/app.css')}}">

        <link rel="canonical" href="@yield('canonical')">
    </head>
    <body>
        <div class="page-wrapper">
            <header class="page-header">
                <div class="inner">
                    <a href="/" class="logo"><img width="192" height="66" src="{{asset('images/logo.svg')}}" alt="eSCAPE - by the Web Bunch" /></a>
                    <nav class="menu-main">
                        <ul class="menu">
                            @auth
                            <li class="menu-item">
                                <a href="/emails">Emails</a>
                            </li>
                            <li class="menu-item">
                                <a href="/reservations">Reservations</a>
                            </li>
                            <li class="menu-item">
                                <a href="/editroom">Rooms</a>
                            </li>
                            <li class="menu-item">
                                <a class="dropdown-item logoutbtn" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </li>
                            @endauth
                            {{-- <li class="menu-item"><a class="menu-link" href="#rooms">rooms</a></li>
                            <li class="menu-item active"><a class="menu-link" href="#">faq</a></li>
                            <li class="menu-item"><a class="menu-link" href="#">blog</a></li>
                            <li class="menu-item"><a class="menu-link" href="#">about</a></li>
                            <li class="menu-item"><a class="menu-link" href="#">contact</a></li> --}}
                        </ul>
                    </nav>
                    <nav class="menu-help">
                        @hasSection('nobutton')

                        @else
                            <ul class="menu">
                                <li class="menu-item"><a class="book-button" href="/book">Book Now!</a></li>
                                {{-- <li class="menu-item"><a class="menu-link search" href="#">Search</a></li> --}}
                                {{-- <li class="menu-item"><a class="menu-link login" href="#">Sign in</a></li> --}}
                            </ul>
                        @endif
                    </nav>
                </div>
            </header>
            <div class="page-content">
                @yield('content')
            </div>
            <footer class="page-footer">
                <div class="inner">
                    <a href="/" class="footer-item footer-item--logo logo"><img width="192" height="66" src="{{asset('images/logo.svg')}}" alt="eSCAPE - by the Web Bunch" /></a>
                    <p class="footer-item footer-item--copyright"><span class="copyright-element date">Copyright 2020</span> <span class="copyright-element divider">-</span> <a class="copyright-element link" target="_blank" rel="noopener" href="https://web-bunch.com/">The Web Bunch</a></p>
                    <div class="footer-item">
                        <a class="footer-link" href="/terms">Terms & Conditions</a>
                        <a class="footer-link" href="/privacy">Privacy Policy</a>
                        <a class="footer-link" href="/instructions">Instructions before you book</a>
                    </div>
                    <div class="footer-item footer-item--social">
                        <a href="https://www.facebook.com/escapeWebBunch" target="_blank" rel="noopener" class="link facebook">Follow us on Facebook</a>
                    </div>
                </div>
            </footer>
        </div>
        <script src="{{ mix('/js/app.js') }}"></script>
        @include('cookieConsent::index')
    </body>
</html>

resources/views/notify.blade.php
@extends('layout')
@section('canonical', 'https://escape.web-bunch.com/notify')
@section('content')
<div class="terms-container">
  <h1 class="booking-title">Please give us your email to notify you when the room "{{ $room->title }}" will be published</h1>
  <form class="booking-form" action="/{{request()->path()}}" method="POST">
    @csrf
    @method('PUT')
    <div class="floating-label notify-email">
      <input type="email" name="email" id="email" placeholder=" " class="form-input" required>
      <label data-label="Email" for="email">Email</label>
    </div>
    <div class="terms notify-terms">
      <label class="terms-label">
        <input type="checkbox" name="terms" id="terms" required>
        <span class="text"><span>I have read and understood the <a href="/terms" target="_blank">Terms & Conditions</a> and  <a href="/privacy" target="_blank">Privacy Policy</a></span></span>
        <span class="checkmark"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" stroke-miterlimit="10" stroke-width="2" d="M21 6L9 18 4 13"></path></svg></span>
      </label>
    </div>
    <div class="submit-button-container">
      <button class="cta-button" type="submit" id="reservation-form-submit">Submit</button>
    </div>
  </form>
</div>
@endsection

resources/views/notifythankyou.blade.php
@extends('layout')

@section('content')
  <h1 class="booking-title">Thank you for your email submition</h1>
  <p class="thankyou-message">We will notify you when "{{ $room->title }}" is published</p>
  <a class="thankyou-back-to-front cta-button" href="/">Back to front</a>
@endsection

resources/views/privacypolicy.blade.php
@extends('layout')
@section('pageTitle', 'Privacy policy | eSCAPE | Online Escape Rooms - by The Web Bunch')
@section('canonical', 'https://escape.web-bunch.com/privacypolicy')
@section('content')
  <div class="container">
    <h1 class="booking-title">Privacy Policy of eSCAPE</h1>
    <div class="terms-container">
      <p>eSCAPE operates the eSCAPE.web-bunch.com website, which provides the SERVICE.</p>

      <p>This page is used to inform website visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Services.</p>

      <p>If you choose to use our Services, then you agree to the collection and use of information in relation with this policy. The Personal Information that we collect are used for providing and improving the Services. We will not use or share your information with anyone except as described in this Privacy Policy.</p>

      <p>The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at <a href="https://escape.web-bunch.com/terms">https://escape.web-bunch.com/terms</a>, unless otherwise defined in this Privacy Policy.</p>

      <h2>Information Collection and Use</h2>

      <p>For a better experience while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to your name, phone number and email. The information that we collect will be used to contact or identify you.</p>

      <h2>Log Data</h2>

      <p>We want to inform you that whenever you visit our Service, we collect information that your browser sends to us that is called Log Data. This Log Data may include information such as your computer’s Internet Protocol ("IP") address, browser version, pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other statistics.</p>

      <h2>Cookies</h2>

      <p>Cookies are files with small amount of data that is commonly used an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your computer’s hard drive.</p>

      <p>Our website uses these "cookies" to collection information and to improve our Services. You have the option to either accept or refuse these cookies, and know when a cookie is being sent to your computer. If you choose to refuse our cookies, you may not be able to use some portions of our Services.</p>

      <p>For more general information on cookies, please read <a target="_blank" rel="noopener" href="https://www.cookieconsent.com/what-are-cookies/">"What Are Cookies"</a>.</p>

      <h2>Service Providers</h2>

      <p>We may employ third-party companies and individuals due to the following reasons:</p>

      <ul>
          <li>To facilitate our Services;</li>
          <li>To provide the Services on our behalf;</li>
          <li>To perform Services-related services; or</li>
          <li>To assist us in analyzing how our Services is used.</li>
      </ul>

      <p>We want to inform our Services users that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.</p>

      <h2>Security</h2>

      <p>We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.</p>

      <h2>Links to Other Sites</h2>

      <p>Our Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

      <p>Children's Privacy</p>

      <p>Our Services do not address anyone under the age of 18. We do not knowingly collect personal identifiable information from children under 18. In the case we discover that a child under 18 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.</p>

      <h2>Changes to This Privacy Policy</h2>

      <p>We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.</p>

      <h2>Contact Us</h2>

      <p>If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.</p>    </div>
  </div>
@endsection

resources/views/reservation_form.blade.php
@extends('layout')
@section('nobutton', 'nobutton')
@section('content')
  <h1 class="booking-title">Reserving <span class="highlight">{{$reservation->room->title}}</span><br />for <span class="highlight">{{ $reservation->formated_time }} (GMT+2)</span></h1>
  <p class="change-link-container">
    <a class="change-link" href="{{route('unlock',$reservation->room->slug)}}">Click here to change</a>
  </p>
  <form class="booking-form" id="reservation-form" action="/{{request()->path()}}" method="POST">
    @csrf
    @method('PUT')
    <label class="styled-radios-label" for="team_size" id="team-size-label">Team Size*</label>
    <div class="styled-radios">
      @foreach ($reservation->room->prices as $size => $price)
        <label class="label">
          <input type="radio" name="team_size" value="{{ $size }}" class="form-radio-input radio-{{ $size }}" required>
          <input type="hidden" value="{{ $price }}" class="hidden-price">
          <span class="text radio-span">{{ $size }} players, <span id="price-span-{{ $price }}">{{ number_format($price, 2) }}</span>€</span>
          <span class="checkmark" role="presentation"></span>
        </label>
      @endforeach
    </div>
    <div class="floating-label">
      <input type="text" name="name" id="name" placeholder="What is your name, adventurer?" class="form-input" required>
      <label data-label="Name*" for="name">Name*</label>
    </div>
    <div class="floating-label">
      <input type="tel" name="phone" id="phone" placeholder="+30 690 000 00 00" class="form-input" required>
      <label data-label="Phone*" for="phone">Phone*</label>
    </div>
    <div class="floating-label">
      <input type="email" name="email" id="email" placeholder="me@example.com" class="form-input" required>
      <label data-label="Email*" for="email">Email*</label>
    </div>
    <div class="floating-label">
      <div class="promo-btn-msg">
      <div id="ajax-message"></div>
      <button id="check-promo" class="small-cta-button">Check code</button>
      </div>
      <input type="text" name="promo_code" id="code" placeholder="Promo code" class="something">
      <label data-label="Promo Code" for="code">Promo Code</label>
    </div>
    <label class="terms-label">
      <input type="checkbox" name="terms" id="terms" required>
      <span class="text"><span>I have read and understood the <a href="/terms" target="_blank">Terms & Conditions</a>, <a href="/privacy" target="_blank">Privacy Policy</a> and <a href="/instructions" target="_blank">Instructions before you book</a> pages.</span></span>
      <span class="checkmark"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" stroke-miterlimit="10" stroke-width="2" d="M21 6L9 18 4 13"></path></svg></span>
    </label>
    <p class="required-message">* Required field.</p>
    <p class="payment-instructions">You will receive a confirmation email, including payment instructions. We currently only accept payment via PayPal. If payment hasn't been received <span class="highlight">12 hours</span> before the time of your reservation, your reservation will be cancelled.
    </p>
    <div class="submit-button-container">
      <button class="cta-button" type="submit" form="reservation-form" id="reservation-form-submit">Submit</button>
    </div>
  </form>


@endsection

resources/views/reservations.blade.php
@extends('layout')

@section('content')
  <div class="container">
    <h1 class="booking-title">Reservations</h1>
    <div class="all-reservations">
      @foreach($reservations->sortBy('time') as $reservation)
        <div class="admin-reservation {{ isset($reservation->email) ? 'booked' : 'available' }}">
          Time: {{ $reservation->time }},
          Room: {{ $reservation->room->title }},
          Name: {{ $reservation->name }},
          Email: {{ $reservation->email }},
          Phone: {{ $reservation->phone }},
          Team size: {{ $reservation->team_size }},
          isPaid: {{ $reservation->paid }},
          id: {{ $reservation->id }}
        <form class="confirm-reservation" action="/reservations/confirm" method="POST">
          @csrf
          @method('PUT')
          <input name="reservation_id" type="hidden" value="{{ $reservation->id }}">
          <button class="{{ isset($reservation->email) && !$reservation->paid ? '' : 'hidden' }}">Confirm Payment</button>
        </form>
        <form class="delete-reservation" action="/reservations/delete" method="POST">
          @csrf
          @method('PUT')
          <input name="reservation_id" type="hidden" value="{{ $reservation->id }}">
          <button class="{{ isset($reservation->email) ? 'hidden' : ' ' }}">Delete</button>
        </form>
        </div>
      @endforeach
    </div>
    <form class="booking-form" action="/reservations/add" method="POST">
    @csrf
    @method('PUT')

    <div class="floating-label">
      <select type="text" name="room" id="room" class="form-input" required>
        @foreach($rooms as $room)
          <option value="{{ $room->id }}">{{ $room->title }}</option>
        @endforeach
      </select>
      <label for="room">Room</label>
    </div>
    <div class="floating-label">
      <input type="date" name="date" step="1">
      <label for="date">Date</label>
    </div>
    <div class="floating-label">
      <input type="time" name="time" step="1">
      <label for="date">Time</label>
    </div>
    <div class="floating-label">
      <select type="text" name="gm" id="gm" class="form-input" required>
          @foreach($gms as $gm)
            <option value="{{ $gm->id }}">{{ $gm->id }}</option>
          @endforeach
      </select>
      <label for="gm">Gm</label>
    </div>
    <div class="submit-button-container">
      <button class="cta-button" type="submit" id="reservation-form-submit">Submit</button>
    </div>
  </form>

  </div>
@endsection

resources/views/rooms.blade.php
@extends('layout')

@section('pageTitle', 'Book an Online Escape Room | eSCAPE - by The Web Bunch')
@section('description', 'Can\'t wait to get trapped online? Choose and Book an Online Escape Room now!')
@section('ogimagecontent', url('/' . trim('images/lazarus-og.jpg', '/\\')))
@section('canonical', 'https://escape.web-bunch.com/book')

@section('content')
<section id="rooms" class="frontpage-section frontpage-section--featured-rooms">
    <div class="frontpage-section-inner">
        <h1 class="frontpage-section-title">Book an Online Escape Room</h1>
        <div class="room-list">
            @foreach($rooms as $room)
            <x-room-teaser :room="$room" />
            @endforeach
        </div>
    </div>
</section>
@endsection

resources/views/thankyou.blade.php
@extends('layout')

@section('content')
  <h1 class="booking-title">Thank you for your reservation</h1>
  <p class="thankyou-message">The details have been sent to your email.</p>
  <a class="thankyou-back-to-front cta-button" href="/">Back to front</a>
@endsection